project_id = "iztvlqhaypkaqowtmhya"

[functions.admin-create-user]
verify_jwt = false

[functions.bootstrap-admin]
verify_jwt = false

[functions.reset-and-seed]
verify_jwt = false

[functions.signup-request]
verify_jwt = false

[functions.approve-signup]
verify_jwt = false

[functions.change-password]
verify_jwt = false
